### ISSUE TITLE
Error when user clicks debug or run before build

### ISSUE THREAD

**Issue by parteekcoder** [ControlCore-Project/concore-editor#87]
Reproduce

1. If user tries to debug or run files before building 

Then server will respond with error 
As there is no check that it will check whether there is build files or not and will fall in error

[2023-02-19 17:12:50,094] ERROR in app: Exception on /debug/sample [POST]
Traceback (most recent call last):
  File "C:\Users\Nitika\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Nitika\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request        
    rv = self.handle_user_exception(e)
  File "C:\Users\Nitika\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function   
    return cors_after_request(app.make_response(f(*args, **kwargs)))  
  File "C:\Users\Nitika\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request        
    rv = self.dispatch_request()
  File "C:\Users\Nitika\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "F:\GSOC\emori-bmi-gsoc\concore\concore\fri\server\main.py", line 92, in debug
    proc = call(["debug"],shell=True , cwd=dir_path)
  File "C:\Users\Nitika\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Nitika\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,      
bprocess.py", line 1438, in _execute_child    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] The directory name is invalid

Should be check at https://github.com/ControlCore-Project/concore/blob/main/fri/server/main.py#L80

this issue can be linked with https://github.com/ControlCore-Project/concore/issues  @pradeeban

**Comment by Rahuljagwani** [comment]
There is no check at https://github.com/ControlCore-Project/concore/blob/main/fri/server/main.py#L80 because till now users are using CLI to perform functions build, debug, run etc. But anyway this has to be solved as after integration calling debug before build will cause problem.

**Comment by pradeeban** [comment]
Yes, that is correct.

We rely on the programming languages (C/C++ and Java) approach where you must compile before you can run.

Our build is like the "compile." Run and debug are like the "run."

https://control-core.readthedocs.io/en/latest/usage.html

This is not necessarily a bug of concore editor. But it is how we have designed concore. We can consider the potential fix of a: invoke "build" first automatically in the backend when you execute "run" or "debug" for the very first time. (So a "run" or "debug" will never fail, regardless of whether one has manually invoked the "build" first. If the folder already exists, the "run" or "debug" won't re-execute the "build." That way, we ensure running again without recompiling too, if that is what the users need. But this can cause confusions among the users too - because they may assume a "run" or "debug" will always recomplie and re-run every time (which won't be the case). 

So, perhaps, a warning saying, "Please click build first" can be the fix for this issue (the warning can be a popup in concore editor, which appears only when the study is never built), without making things too complicated.

This implementation will be part of the GSoC project 1 too.

Keeping the issue open.

**Comment by pradeeban** [comment]
This is fixed. Clsoing.
